---
title: "bank-cluster"
author: "Crystal Tse"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# results='hide' to get rid of text output
```

```{r message = FALSE}
library(mosaic)
library(tidyverse)
library(ggplot2)
library(randomForest)
library(pdp)
library(lubridate)
library(naniar)
library(rpart)
library(dplyr)
library(fastDummies)
library(class)
library(ClustOfVar)


bank = read_delim("bank-additional-full.csv", delim = ";")
bank10 = read_delim("bank-additional.csv", delim = ";")
```


```{r}
# get rid of observations that have unknowns
bank10 <- bank10 %>% replace_with_na_all(condition = ~.x == "unknown")
bank10 <-bank10[complete.cases(bank10), ] # went from 4119 to 3090 obs

# maybe it is worth removing pdays since it only occurs 142 times out of the 3090 obs
sum(bank10$pdays != 999)

# remove duration because it is highly correlated with y (duration = 0 --> no)
bank10 = subset(bank10, select = -c(duration, pdays) )

```

## Hierarchical Clustering

```{r}
X.quanti <- PCAmixdata::splitmix(bank10)$X.quanti
X.quali <- PCAmixdata::splitmix(bank10)$X.quali
X.quali = mutate(X.quali,
                default = ifelse(default == "yes", "yes_default", "no_default"),
                housing = ifelse(housing == "yes", "yes_housing", "no_housing"),
                loan = ifelse(loan == "yes", "yes_loan", "no_loan"))
# Center and scale the quantitative data
X.quanti_sc = scale(X.quanti, center=TRUE, scale=TRUE)

# Extract the centers and scales from the rescaled data (which are named attributes)
mu = attr(X.quanti_sc,"scaled:center")
sigma = attr(X.quanti_sc,"scaled:scale")

# can also try the iclust() function within the psych package
# or clusters() function in the igraph package
# https://stackoverflow.com/questions/51160951/clustering-analysis/51161138#51161138
tree <- hclustvar(X.quanti_sc, X.quali)
plot(tree)  # dendrogram

```

```{r}
# X.quanti = PCAmixdata::splitmix(bank10)$X.quanti
# X.quali = PCAmixdata::splitmix(bank10)$X.quali
# X.quali = mutate(X.quali,
#                 default = ifelse(default == "yes", "yes_default", "no_default"),
#                 housing = ifelse(housing == "yes", "yes_housing", "no_housing"),
#                 loan = ifelse(loan == "yes", "yes_loan", "no_loan"))


# stability: bootstrap approach to help identify number of clusters
stab = stability(tree,B=60)
# plot(stab,main="Stability of the partitions")
# boxplot(stab$matCR[,1:7])
```



```{r}
part<-cutreevar(tree,6) #cut of the tree
summary(part)
res.plot <- plot.clustvar(part) # plot of loadings of each cluster
res.plot$coord.quanti
res.plot$coord.levels
```




```{r}
#the partition from the hierarchical clustering is chosen as initial partition
X.quanti <- PCAmixdata::splitmix(bank10)$X.quanti
X.quali <- PCAmixdata::splitmix(bank10)$X.quali
X.quali = mutate(X.quali,
                default = ifelse(default == "yes", "yes_default", "no_default"),
                housing = ifelse(housing == "yes", "yes_housing", "no_housing"),
                loan = ifelse(loan == "yes", "yes_loan", "no_loan"))

# Center and scale the quantitative data
X.quanti_sc = scale(X.quanti, center=TRUE, scale=TRUE)

# Extract the centers and scales from the rescaled data (which are named attributes)
mu = attr(X.quanti_sc,"scaled:center")
sigma = attr(X.quanti_sc,"scaled:scale")

part_init <- cutreevar(tree,5)$cluster
part2 <- kmeansvar(X.quanti_sc, X.quali, init=part_init, matsim=TRUE)
# Gain in cohesion (in %):  38.74
summary(part2)
part2$sim
```


```{r}

## K-means clustering revised for qualitative and quantitative mixed data
# maybe edit the number of clusters (init) to be optimal  ##debug
# choice of the number of clusters
X.quanti <- PCAmixdata::splitmix(bank10)$X.quanti
X.quali <- PCAmixdata::splitmix(bank10)$X.quali
X.quali = mutate(X.quali,
                 default = ifelse(default == "yes", "yes_default", "no_default"),
                 housing = ifelse(housing == "yes", "yes_housing", "no_housing"),
                 loan = ifelse(loan == "yes", "yes_loan", "no_loan"))

# Center and scale the quantitative data
X.quanti_sc = scale(X.quanti, center=TRUE, scale=TRUE)

# Extract the centers and scales from the rescaled data (which are named attributes)
mu = attr(X.quanti_sc,"scaled:center")
sigma = attr(X.quanti_sc,"scaled:scale")

## debug also increase iter.max later
bank_kmeans = kmeansvar(X.quanti = X.quanti_sc, 
                        X.quali = X.quali, 
                        init = 3,
                        iter.max = 10,
                        nstart = 1, matsim = TRUE)

plot.clustvar(bank_kmeans)


```





